### PR TITLE
Enabled TLS Encryption

### PR DESCRIPTION
**Pull request by keith-gamble**
This pull request adds a new container to the docker-compose file, `step-ca`, which runs a certificate authority using the `smallstep/step-ca` image. The StepCA container will enable us to issue and manage our own certificates for use with Traefik, instead of relying on third-party certificate authorities.

To use our own certificates with Traefik, we have also updated the proxy container to use the default certificate resolver and to mount our new StepCA root certificate as a volume. This will allow Traefik to automatically obtain and renew SSL/TLS certificates signed by our StepCA.

With this configuration, we will have full control over our SSL/TLS certificates and can use them to enable HTTPS and secure communication between Traefik and our services. Additionally, using our own certificate authority will improve the security and trustworthiness of our infrastructure.

### CODE REVIEW

**Comment by tyler-kaim1** [comment]
Whenever I try to run the ./generate-certs.sh I get an error:

`Copying the CA Config to the step-ca container...
Error response from daemon: Container 1788bf318a84e63c81dee647bdb012563440f165d3299e8b797cdeb8e7950c6c is not running
Error response from daemon: mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/f7163902c0350cd9056b32d57bf3153c697d9b5874d54c1ef3cdb5a978a7974a:/var/lib/docker/overlay2/babc8066720e9c574d257b5c7194b6dcd837886a64759bed49a473e688b8c1ad/merged/certs, flags: 0x5000: no such file or directory
Restarting the step-ca container to load the new config...
Restarting step-ca ... error

ERROR: for step-ca  Cannot restart container 1788bf318a84e63c81dee647bdb012563440f165d3299e8b797cdeb8e7950c6c: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/f7163902c0350cd9056b32d57bf3153c697d9b5874d54c1ef3cdb5a978a7974a" to rootfs at "/certs": mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/f7163902c0350cd9056b32d57bf3153c697d9b5874d54c1ef3cdb5a978a7974a:/certs (via /proc/self/fd/14), flags: 0x5000: no such file or directory: unknown
Waiting for step-ca container to be ready...`

It just continues to wait for the step-ca container to be ready afterwards. Tried to look into it a bit and not sure what's causing this?

**Review by tyler-kaim1 — CHANGES_REQUESTED** [review]
Whenever I try to run the `./generate-certs.sh` I get an error:

```
Copying the CA Config to the step-ca container...
Restarting the step-ca container to load the new config...
Restarting step-ca ... done
Getting the password from the step-ca container...
Getting the fingerprint from the step-ca container...
Bootstrapping the CA...
Creating the certificate for the localtest.me domain...
✔ Provisioner: admin (JWK) [kid: v0eMAhVmBx9B1hyVNI86ehRZn2sa1E_44BQIhKiU1O0]
error allocating terminal: open /dev/tty: no such device or address
Exporting the root CA certificate...
Your certificate has been saved in ./root_ca.crt.
Copying the root CA certificate to the host...
open /home/tylerkaim/traefik-proxy/certs/root_ca.crt: permission denied
Restarting the traefik container to load the new certificates...
Restarting proxy ... done
Creating certificate chain for the localtest.me domain...
./generate-certs.sh: line 50: ./certs/localtest.me.chain.crt: Permission denied
Creating a bundle for the localtest.me domain...
Can't open certs/localtest.me.key for reading, No such file or directory
139965718615360:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('certs/localtest.me.key','r')
139965718615360:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load private key
Certificates generated successfully.
```

Then I'm not able to access proxy.localtest.me.

**Comment by keith-gamble** [comment]
I believe that the error is when it tries to create a year long cert. Originally I created the script with a 24h cert but it was too short, it looks to be erroring out there.

Try to do a full `docker compose down -d` on that stack, then verify the volumes for that stack are gone, and then try again. You may have done this before I added the `ca-config.json` script that increases the time limit for the certificates.

This shouldn't be an issue after this PR, since I believe you had an early version of the PR originally.

**Comment by keith-gamble** [comment]
I actually realized an issue with the CA password generation, try to re-pull and do this now. However the specific branch up there now currently has my next feature in it, so if this works we can break up that PR.

**Review by tyler-kaim1 — CHANGES_REQUESTED** [review]
Not sure what happened but the folder "certs" was owned by root and I had to manually switch it over to be owned by me. Should this be included in the README or did I do something wrong?

Besides this, I was able to get everything working.

**Pull request closed without merging**
